import Provider from "@/component/Provider";
import {CustomProvider} from "@/component/CustomProvider";
import '@/style/style.css'

export const metadata = {
    title: 'Dev Games',
    description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
        <body>
        <CustomProvider>
            <Provider>
                {children}
            </Provider>
        </CustomProvider>
        </body>
        </html>
    )
}