import Provider from "@/component/Provider";
import '@/style/style.css'

export const metadata = {
    title: 'Dev Games',
    description: 'Generated by Next.js'
}

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
        <body>
        <Provider>
            {children}
        </Provider>
        </body>
        </html>
    )
}